import os
import requests
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.chart.data import CategoryChartData
from pptx.enum.chart import XL_CHART_TYPE

# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------
PRIMARY_COLOR = RGBColor(0, 51, 102)  # Navy Blue
TEXT_COLOR = RGBColor(64, 64, 64)     # Dark Grey
FOOTER_TEXT = "Strictly Private & Confidential - Generated by Kelp AI"

def download_image(query, filename="temp_img.jpg"):
    """Downloads a generic stock image based on the query."""
    if not query: return None
    print(f"   [Img] Fetching image for: '{query}'...")
    safe_query = query.replace(" ", ",").lower()
    url = f"https://loremflickr.com/800/600/{safe_query}"
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            with open(filename, 'wb') as f:
                f.write(response.content)
            return filename
    except Exception as e:
        print(f"   [Warning] Image download failed: {e}")
    return None

def set_branding(slide):
    # Footer
    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(7), Inches(9), Inches(0.5))
    tf = txBox.text_frame
    p = tf.paragraphs[0]
    p.text = FOOTER_TEXT
    p.font.size = Pt(9)
    p.font.color.rgb = RGBColor(128, 128, 128)
    p.alignment = PP_ALIGN.CENTER

def create_native_chart(slide, chart_data_dict):
    if not chart_data_dict: return
    chart_data = CategoryChartData()
    chart_data.categories = chart_data_dict.get("labels", [])
    chart_data.add_series('Series 1', chart_data_dict.get("values", []))
    x, y, cx, cy = Inches(5.5), Inches(2.5), Inches(4), Inches(3)
    try:
        chart = slide.shapes.add_chart(XL_CHART_TYPE.COLUMN_CLUSTERED, x, y, cx, cy, chart_data).chart
        chart.chart_title.text_frame.text = chart_data_dict.get("title", "Metrics")
    except: pass

def generate_styled_ppt(ppt_data, output_file):
    prs = Presentation()
    slides_list = ppt_data.get("slides", [])
    
    for i, slide_content in enumerate(slides_list):
        slide = prs.slides.add_slide(prs.slide_layouts[6]) # Blank layout
        set_branding(slide)
        
        # 1. Title
        title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.4), Inches(9), Inches(1))
        title_tf = title_shape.text_frame
        title_p = title_tf.paragraphs[0]
        title_p.text = slide_content.get("title", "Slide")
        title_p.font.bold = True
        title_p.font.size = Pt(28)
        title_p.font.color.rgb = PRIMARY_COLOR

        # 2. Bullets (FIXED LOOP)
        content_box = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(5), Inches(5))
        tf = content_box.text_frame
        tf.word_wrap = True
        
        bullets = slide_content.get("bullets", [])
        
        # --- THE FIX IS HERE ---
        for index, bullet in enumerate(bullets):
            # Use the existing first paragraph for item 0, add new ones for the rest
            if index == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()
            
            text_content = bullet["text"] if isinstance(bullet, dict) else str(bullet)
            p.text = "• " + text_content
            p.font.size = Pt(14)
            p.font.color.rgb = TEXT_COLOR
            p.space_after = Pt(12) # Nice spacing between bullets

        # 3. Visuals (Chart or Image)
        if slide_content.get("chart_data"):
             create_native_chart(slide, slide_content["chart_data"])
        elif slide_content.get("image_query"):
             img_filename = f"temp_img_{i}.jpg"
             img_path = download_image(slide_content["image_query"], img_filename)
             if img_path:
                 slide.shapes.add_picture(img_path, Inches(6), Inches(2), width=Inches(3.5))

    prs.save(output_file)
    print(f"PPT Saved: {output_file}")
    
    # Cleanup
    for i in range(len(slides_list)):
        if os.path.exists(f"temp_img_{i}.jpg"): os.remove(f"temp_img_{i}.jpg")